# This file was autogenerated by android-configure.sh. Do not edit !
OS          := linux-x86
HOST_OS     := linux
HOST_ARCH   := x86
CC          := ./../../prebuilts/tools/gcc-sdk/gcc
HOST_CC     := ./../../prebuilts/tools/gcc-sdk/gcc
LD          := ./../../prebuilts/tools/gcc-sdk/gcc
AR          := ar
CFLAGS      :=  -m32
LDFLAGS     :=  -m32

TARGET_ARCH       := arm
HOST_PREBUILT_TAG := linux-x86
HOST_EXEEXT       := 
PREBUILT          := 
PREBUILTS         := /home/wz/WORKING_DIRECTORY/prebuilts/misc/linux-x86
SRC_PATH          := /home/wz/WORKING_DIRECTORY/external/qemu
CONFIG_COREAUDIO  := no
CONFIG_WINAUDIO   := no
CONFIG_ESD        := yes
CONFIG_ALSA       := yes
CONFIG_OSS        := yes
CONFIG_PULSEAUDIO := yes
BUILD_STANDALONE_EMULATOR := true
BUILD_DEBUG_EMULATOR := true
ANDROID_SDK_TOOLS_REVISION := 22.0.1
QEMU_OPENGLES_INCLUDE    := /home/wz/WORKING_DIRECTORY/sdk/emulator/opengl/host/include
QEMU_OPENGLES_LIBS       := /home/wz/WORKING_DIRECTORY/out/host/linux-x86/lib
